import "./bootstrap";
import "../css/app.css";
import $ from "jquery";
import {
    createIcons,
    CircleAlert,
    SquarePen,
    Send,
    MoveLeft,
    Plus,
    MoveUp,
    MoveDown,
    Eye,
    Edit,
    ChevronLeft,
    ChevronRight,
    Search,
    RefreshCcw,
    FileCheck,
    LogOut,
    ArrowLeft,
    Menu,
    X,
    ClipboardClock,
    FileClock,
    Check,
    Bell,
    Home,
    Users,
    Building2,
    MapPin,
    ShieldCheck,
    FileText,
    Inbox,
    Clock,
    CircleCheckBig,
    XCircle,
    Ban,
    UsersRound,
    FolderOpen,
    UserRound,
    ImageOff,
    EllipsisVertical,
    FileSliders,
    FileType,
    ChevronUp,
    ChevronDown,
    ArrowRight,
    Trash2,
    Settings,
    GitBranch,
    PackageCheck,
    ClipboardCheck,
    BarChart3,
} from "lucide";

createIcons({
    icons: {
        CircleAlert,
        SquarePen,
        Send,
        MoveLeft,
        MoveUp,
        MoveDown,
        Plus,
        Eye,
        Edit,
        ChevronLeft,
        ChevronRight,
        Search,
        RefreshCcw,
        FileCheck,
        LogOut,
        ArrowLeft,
        ArrowRight,
        Menu,
        X,
        FileClock,
        Check,
        Bell,
        Home,
        Users,
        Building2,
        MapPin,
        ShieldCheck,
        FileText,
        Inbox,
        Clock,
        CircleCheckBig,
        XCircle,
        Ban,
        UsersRound,
        FolderOpen,
        UserRound,
        ImageOff,
        EllipsisVertical,
        FileSliders,
        FileType,
        ChevronUp,
        ChevronDown,
        Trash2,
        Settings,
        GitBranch,

    },
});

// Expose lucide globally for dynamic content
window.lucide = {
    createIcons: () => createIcons({
        icons: {
            CircleAlert,
            SquarePen,
            Send,
            MoveLeft,
            MoveUp,
            MoveDown,
            Plus,
            Eye,
            Edit,
            ChevronLeft,
            ChevronRight,
            Search,
            RefreshCcw,
            FileCheck,
            LogOut,
            ArrowLeft,
            ArrowRight,
            Menu,
            X,
            FileClock,
            Check,
            Bell,
            Home,
            Users,
            Building2,
            MapPin,
            ShieldCheck,
            FileText,
            Inbox,
            Clock,
            CircleCheckBig,
            XCircle,
            Ban,
            UsersRound,
            FolderOpen,
            UserRound,
            ImageOff,
            EllipsisVertical,
            FileSliders,
            FileType,
            ChevronUp,
            ChevronDown,
            Trash2,
            Settings,
            GitBranch,
            PackageCheck,
            ClipboardCheck,
            BarChart3
        },
    })
};


window.$ = window.jQuery = $;

document.addEventListener('DOMContentLoaded', function() {
    const observer = new MutationObserver(() => {
        createIcons();
    });

    observer.observe(document.body, {
        childList: true,
        subtree: true
    });
});